version: "3"
services:
  db-psql:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  independent_news:
    image: independent_news
    build:
      context: ./independent_news
    container_name: independent_news
    depends_on:
      - db-psql
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: ["python", "run.py"]

  news_crawler:
    image: news_crawler
    build:
      context: ./independent_news
    container_name: news_crawler
    depends_on:
      - db-psql
    env_file:
      - .env
    command: ["python", 'news_crawler/usa_today.py']

  news_gui:
    image: news_gui
    build: 
      context: ./news_gui
    container_name: news_gui
    depends_on:
      - news_crawler
    ports:
      - "8080:8080"
    command: [ "http-server", "dist" ]

volumes:
  db-data:
    driver: local



